In [8]:
from dotenv import load_dotenv
import os
import pandas as pd

In [3]:
load_dotenv()

True

In [5]:
from openai import OpenAI

client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

In [ ]:
# response = client.embeddings.create(model="text-embedding-3-small", input="안녕하세요 임베딩 테스트입니다.")
# len(response.data[0].embedding)

1536

In [9]:
# 문서
data = pd.read_csv("../data/11-1_뉴스정제.csv")

In [11]:
doc_list = data['정제본문'].head(30).tolist()

In [12]:
import time
# 벡터 문서 -> 임베딩

start = time.time() # 시작 시간
doc_response = client.embeddings.create(model="text-embedding-3-small", input=doc_list)
api_time = time.time() - start
print(api_time)

0.7158634662628174

In [13]:
# 1. 유사도 계산
from sklearn.metrics.pairwise import cosine_similarity

In [19]:
doc_response.data[0].embedding
# doc_response.data

[-0.020660400390625,
 -0.0028591156005859375,
 0.034210205078125,
 0.034271240234375,
 0.01126861572265625,
 0.0037384033203125,
 0.0038433074951171875,
 0.0570068359375,
 -0.0007305145263671875,
 -0.059722900390625,
 -0.034515380859375,
 -0.0190277099609375,
 0.0014085769653320312,
 -0.04046630859375,
 0.0245513916015625,
 -0.011505126953125,
 -0.004791259765625,
 -0.0009984970092773438,
 0.0478515625,
 -0.012451171875,
 -0.0214691162109375,
 -0.02880859375,
 0.01332855224609375,
 0.006488800048828125,
 -0.007358551025390625,
 -0.018646240234375,
 0.01395416259765625,
 0.0479736328125,
 -0.0010051727294921875,
 -0.01537322998046875,
 -0.03497314453125,
 -0.03692626953125,
 0.0318603515625,
 0.015472412109375,
 0.0149078369140625,
 0.0260772705078125,
 0.0093994140625,
 0.0213623046875,
 0.0309295654296875,
 -0.00678253173828125,
 0.03057861328125,
 -0.006877899169921875,
 0.003173828125,
 0.004497528076171875,
 0.0196990966796875,
 0.0259857177734375,
 -0.0028095245361328125,
 0.001773834228515625,
 0.05328369140625,
 0.0225830078125,
 0.048675537109375,
 0.005176544189453125,
 0.0172119140625,
 -0.05963134765625,
 -0.0228729248046875,
 0.00550079345703125,
 -0.04766845703125,
 -0.010711669921875,
 -0.0032291412353515625,
 0.004589080810546875,
 0.058624267578125,
 -0.03082275390625,
 0.0263824462890625,
 0.05084228515625,
 0.024627685546875,
 0.009521484375,
 0.057373046875,
 -0.01442718505859375,
 -0.0086822509765625,
 0.0284423828125,
 -0.00067138671875,
 0.0164337158203125,
 0.057281494140625,
 0.0203094482421875,
 -0.007305145263671875,
 -0.0234527587890625,
 -0.0036106109619140625,
 0.0126953125,
 0.004650115966796875,
 -0.0016565322875976562,
 0.0548095703125,
 -0.0022735595703125,
 0.0230712890625,
 0.0225372314453125,
 -0.0310211181640625,
 0.01232147216796875,
 -0.0272674560546875,
 -0.007495880126953125,
 -0.01507568359375,
 0.06768798828125,
 0.01300048828125,
 0.034149169921875,
 0.03094482421875,
 0.03057861328125,
 0.0196685791015625,
 -0.004985809326171875,
 -0.044281005859375,
 0.0005297660827636719,
 0.0517578125,
 0.06707763671875,
 -0.01404571533203125,
 -0.053436279296875,
 0.0275115966796875,
 -0.046478271484375,
 0.039459228515625,
 0.00916290283203125,
 0.051483154296875,
 -0.034393310546875,
 0.005970001220703125,
 -0.005748748779296875,
 0.0081787109375,
 -0.004421234130859375,
 0.016082763671875,
 0.0278472900390625,
 0.036956787109375,
 -0.047454833984375,
 0.04998779296875,
 -0.038726806640625,
 0.000949859619140625,
 0.015045166015625,
 0.0033092498779296875,
 0.0113983154296875,
 -0.003505706787109375,
 -0.013671875,
 -0.0340576171875,
 0.019805908203125,
 -0.005580902099609375,
 -0.0137786865234375,
 -0.06793212890625,
 -0.0367431640625,
 -0.044464111328125,
 -0.028411865234375,
 -0.018768310546875,
 -0.038970947265625,
 0.047393798828125,
 0.0230865478515625,
 -0.06805419921875,
 -0.047454833984375,
 -0.025787353515625,
 -0.052581787109375,
 0.041229248046875,
 -0.0132598876953125,
 0.04730224609375,
 0.001834869384765625,
 -0.0161285400390625,
 -0.01519775390625,
 0.014007568359375,
 0.00583648681640625,
 -0.0313720703125,
 0.05938720703125,
 -0.0124053955078125,
 -0.0137939453125,
 0.0221405029296875,
 -0.06878662109375,
 -0.0011444091796875,
 -0.005741119384765625,
 -0.0250091552734375,
 0.0540771484375,
 -0.00399017333984375,
 0.0006003379821777344,
 0.01508331298828125,
 -0.0093841552734375,
 -0.0080718994140625,
 0.00728607177734375,
 0.041168212890625,
 0.01145172119140625,
 -0.036590576171875,
 0.0222015380859375,
 -0.051513671875,
 0.01030731201171875,
 0.0240325927734375,
 0.05615234375,
 0.039459228515625,
 0.07763671875,
 0.0023555755615234375,
 0.0212860107421875,
 0.052001953125,
 0.027099609375,
 -0.0188140869140625,
 0.0150909423828125,
 0.00970458984375,
 0.01300048828125,
 -0.0014400482177734375,
 0.0252532958984375,
 -0.0204925537109375,
 -0.032318115234375,
 0.0301055908203125,
 -0.052093505859375,
 0.0222930908203125,
 0.07513427734375,
 -0.045745849609375,
 0.035186767578125,
 0.00890350341796875,
 0.032562255859375,
 -0.007564544677734375,
 -0.017120361328125,
 -0.01335906982421875,
 0.0231170654296875,
 -0.01073455810546875,
 0.0032901763916015625,
 -0.0286102294921875,
 -0.0086212158203125,
 0.0208740234375,
 -0.00765228271484375,
 -0.022796630859375,
 -0.011199951171875,
 0.01395416259765625,
 -0.0036487579345703125,
 0.019134521484375,
 0.011322021484375,
 0.0343017578125,
 -0.0169525146484375,
 -0.00798797607421875,
 0.044769287109375,
 0.0124969482421875,
 -0.0654296875,
 -0.037384033203125,
 0.04718017578125,
 -0.06134033203125,
 -0.0196380615234375,
 0.038604736328125,
 0.046844482421875,
 0.0164947509765625,
 0.055206298828125,
 -0.020538330078125,
 0.0066070556640625,
 -0.002933502197265625,
 -0.0275421142578125,
 -0.0254669189453125,
 -0.0144500732421875,
 0.005245208740234375,
 -0.0003535747528076172,
 -0.036163330078125,
 0.0215911865234375,
 0.038116455078125,
 -0.004241943359375,
 0.0226593017578125,
 -0.0048828125,
 -0.00885009765625,
 0.014617919921875,
 0.04058837890625,
 0.058197021484375,
 0.05487060546875,
 0.034393310546875,
 0.0088958740234375,
 0.0262298583984375,
 0.005237579345703125,
 -0.039642333984375,
 -0.0191192626953125,
 0.06622314453125,
 0.006206512451171875,
 0.07275390625,
 0.041473388671875,
 0.01702880859375,
 -0.02056884765625,
 -0.00429534912109375,
 -0.0107421875,
 0.0556640625,
 -0.0296630859375,
 0.0092926025390625,
 0.00800323486328125,
 0.0162811279296875,
 0.037139892578125,
 -0.00731658935546875,
 -0.0168609619140625,
 0.04412841796875,
 0.006267547607421875,
 0.07696533203125,
 -0.00630950927734375,
 0.006870269775390625,
 -0.034820556640625,
 -0.03955078125,
 -0.0192718505859375,
 -0.051300048828125,
 -0.007232666015625,
 -0.003986358642578125,
 -0.045166015625,
 0.0114593505859375,
 -0.0003643035888671875,
 -0.0217437744140625,
 0.001712799072265625,
 0.00563812255859375,
 -0.0181427001953125,
 -0.0263519287109375,
 -0.0248260498046875,
 0.04205322265625,
 -0.0673828125,
 0.0250701904296875,
 -0.022796630859375,
 0.015380859375,
 0.01549530029296875,
 -0.0311431884765625,
 -0.0013256072998046875,
 -0.0302734375,
 -0.08233642578125,
 0.011016845703125,
 -0.01255035400390625,
 -0.061981201171875,
 -0.032440185546875,
 -0.014404296875,
 -0.0029163360595703125,
 -0.0213165283203125,
 -0.0309295654296875,
 -0.0024852752685546875,
 -0.00533294677734375,
 0.035369873046875,
 -0.038299560546875,
 0.038055419921875,
 0.040313720703125,
 0.020233154296875,
 -0.0184783935546875,
 -0.014923095703125,
 -0.005619049072265625,
 -0.01258087158203125,
 -0.004566192626953125,
 -0.0296630859375,
 0.041412353515625,
 0.0311431884765625,
 -0.0029449462890625,
 0.00576019287109375,
 0.023651123046875,
 -0.0279083251953125,
 0.0103607177734375,
 -0.052337646484375,
 -0.0019989013671875,
 0.009613037109375,
 0.0247039794921875,
 -0.01122283935546875,
 -0.00928497314453125,
 -0.0260162353515625,
 0.00910186767578125,
 0.021087646484375,
 0.017913818359375,
 0.01421356201171875,
 0.0171051025390625,
 -0.053466796875,
 -0.01348876953125,
 0.045166015625,
 0.035430908203125,
 -0.024078369140625,
 -0.0258026123046875,
 -0.01265716552734375,
 -0.0158233642578125,
 -0.039276123046875,
 0.03546142578125,
 -0.049591064453125,
 0.04718017578125,
 -0.0234222412109375,
 0.0005044937133789062,
 0.027435302734375,
 0.003662109375,
 -0.0212554931640625,
 0.005863189697265625,
 0.020660400390625,
 0.0059661865234375,
 -0.06396484375,
 -0.0372314453125,
 0.055938720703125,
 -0.03302001953125,
 0.0098114013671875,
 0.031494140625,
 -0.035003662109375,
 0.023406982421875,
 0.040618896484375,
 0.042327880859375,
 -0.01052093505859375,
 -0.0025234222412109375,
 0.01116180419921875,
 0.008087158203125,
 0.04425048828125,
 -0.0211944580078125,
 0.003570556640625,
 0.0188751220703125,
 0.007770538330078125,
 -0.026153564453125,
 0.0274658203125,
 0.0181732177734375,
 0.0277557373046875,
 -0.01471710205078125,
 -0.0325927734375,
 -0.002979278564453125,
 -0.03387451171875,
 -0.00748443603515625,
 -0.0382080078125,
 0.0004925727844238281,
 -0.007579803466796875,
 -0.010528564453125,
 0.004665374755859375,
 -0.007701873779296875,
 0.0271453857421875,
 0.040985107421875,
 -0.0282440185546875,
 0.017333984375,
 -0.020416259765625,
 -0.02008056640625,
 0.001316070556640625,
 0.0157470703125,
 0.0027561187744140625,
 -0.029815673828125,
 -0.006488800048828125,
 0.01470947265625,
 -0.046966552734375,
 0.0165557861328125,
 0.025970458984375,
 -0.0323486328125,
 -0.0301361083984375,
 0.0035076141357421875,
 -0.0296630859375,
 0.01910400390625,
 -0.033477783203125,
 0.035186767578125,
 -0.048126220703125,
 0.0229644775390625,
 -0.0237274169921875,
 -0.0498046875,
 -0.03485107421875,
 -0.0287933349609375,
 0.0030078887939453125,
 -0.00914764404296875,
 0.01297760009765625,
 0.00460052490234375,
 0.01342010498046875,
 -0.0142822265625,
 0.041656494140625,
 0.0300140380859375,
 -0.01708984375,
 -0.047454833984375,
 0.030731201171875,
 0.00014412403106689453,
 -0.03204345703125,
 -0.025390625,
 -0.09423828125,
 -0.011199951171875,
 -0.033966064453125,
 0.00238037109375,
 0.056365966796875,
 -0.0010690689086914062,
 0.007221221923828125,
 0.0170745849609375,
 0.01364898681640625,
 0.0092010498046875,
 0.002834320068359375,
 0.0019626617431640625,
 0.00995635986328125,
 -0.0494384765625,
 0.025054931640625,
 0.01763916015625,
 0.020233154296875,
 -0.026092529296875,
 0.0268096923828125,
 0.0080718994140625,
 -0.027069091796875,
 -0.0260009765625,
 0.00365447998046875,
 -0.037994384765625,
 0.01407623291015625,
 -0.0121307373046875,
 -0.0087432861328125,
 0.04791259765625,
 -0.037994384765625,
 0.034271240234375,
 0.0400390625,
 0.0088043212890625,
 0.0224456787109375,
 0.0167999267578125,
 -0.0138702392578125,
 0.0022792816162109375,
 0.0504150390625,
 0.003185272216796875,
 -0.0276336669921875,
 0.0345458984375,
 -0.01678466796875,
 0.0107879638671875,
 0.03167724609375,
 0.01102447509765625,
 -0.043487548828125,
 -0.01505279541015625,
 0.005443572998046875,
 -0.0087890625,
 0.01031494140625,
 -0.02850341796875,
 -0.048797607421875,
 -0.0243988037109375,
 -0.0222930908203125,
 0.0309295654296875,
 -0.01268768310546875,
 0.0201416015625,
 -0.0411376953125,
 0.027679443359375,
 -0.0537109375,
 -0.02349853515625,
 0.05865478515625,
 0.05316162109375,
 -0.002353668212890625,
 0.01947021484375,
 0.0302734375,
 -0.03887939453125,
 -0.009857177734375,
 -0.0187835693359375,
 0.01194000244140625,
 0.0226287841796875,
 -0.035858154296875,
 -0.0148773193359375,
 -0.0203857421875,
 0.013671875,
 -0.008514404296875,
 -0.047332763671875,
 -0.0164947509765625,
 0.034759521484375,
 -0.019989013671875,
 0.0394287109375,
 0.002185821533203125,
 -0.0100250244140625,
 0.0155792236328125,
 0.0300750732421875,
 0.0149993896484375,
 0.013916015625,
 0.0217437744140625,
 0.0297698974609375,
 0.0251617431640625,
 -0.01337432861328125,
 -0.004238128662109375,
 -0.0033245086669921875,
 -0.00811767578125,
 0.0367431640625,
 -0.014068603515625,
 -0.0204010009765625,
 -0.034698486328125,
 0.01303863525390625,
 0.0185699462890625,
 -0.032958984375,
 0.004505157470703125,
 0.0202178955078125,
 -0.0212554931640625,
 0.021820068359375,
 -0.01800537109375,
 0.0246429443359375,
 -0.017120361328125,
 0.0029735565185546875,
 0.0023746490478515625,
 0.003498077392578125,
 -0.0067291259765625,
 0.044769287109375,
 -0.046661376953125,
 0.0020771026611328125,
 -0.006191253662109375,
 -0.006015777587890625,
 -0.0128173828125,
 0.026885986328125,
 0.012786865234375,
 0.04400634765625,
 0.002315521240234375,
 -0.03448486328125,
 0.0180816650390625,
 0.018524169921875,
 0.036376953125,
 0.0129547119140625,
 -0.015289306640625,
 0.051422119140625,
 0.006160736083984375,
 0.0205535888671875,
 0.00855255126953125,
 0.01003265380859375,
 0.0111236572265625,
 -0.025634765625,
 -0.017974853515625,
 0.04180908203125,
 0.01910400390625,
 -0.0289306640625,
 0.01422119140625,
 0.0062255859375,
 -0.00757598876953125,
 -0.0008912086486816406,
 0.01715087890625,
 -0.0008625984191894531,
 -0.004215240478515625,
 0.0012426376342773438,
 -0.032135009765625,
 0.0156402587890625,
 -0.0260162353515625,
 0.00110626220703125,
 -0.008056640625,
 0.049163818359375,
 -0.0091400146484375,
 -0.0164794921875,
 0.020050048828125,
 0.00909423828125,
 0.0019626617431640625,
 0.022125244140625,
 0.01812744140625,
 -0.0467529296875,
 0.0068511962890625,
 0.0211944580078125,
 -0.023712158203125,
 0.035186767578125,
 -0.0227813720703125,
 -0.0269317626953125,
 -0.0260467529296875,
 0.057159423828125,
 0.0062713623046875,
 0.003910064697265625,
 -0.03546142578125,
 0.01568603515625,
 -0.034637451171875,
 -0.028411865234375,
 -0.07012939453125,
 0.019561767578125,
 -0.021240234375,
 -0.0188751220703125,
 -0.026580810546875,
 0.0030517578125,
 0.01922607421875,
 -0.0219879150390625,
 0.01366424560546875,
 -0.0174102783203125,
 0.0258941650390625,
 -0.032867431640625,
 0.0153350830078125,
 0.0235595703125,
 -0.049835205078125,
 0.005096435546875,
 0.0105743408203125,
 0.02044677734375,
 -0.0133819580078125,
 0.00994873046875,
 -0.0047454833984375,
 0.0012083053588867188,
 0.0294952392578125,
 -0.026458740234375,
 -0.01363372802734375,
 -0.004974365234375,
 -0.0198211669921875,
 0.028839111328125,
 -0.032562255859375,
 0.006061553955078125,
 0.034393310546875,
 -0.0087127685546875,
 0.0289154052734375,
 -0.0102081298828125,
 0.03436279296875,
 0.0091552734375,
 -0.004467010498046875,
 -0.0171966552734375,
 -0.03216552734375,
 0.004703521728515625,
 0.02783203125,
 0.02984619140625,
 -0.0191497802734375,
 0.0204010009765625,
 -0.00923919677734375,
 0.00653076171875,
 0.0208892822265625,
 -0.031707763671875,
 0.01490020751953125,
 0.01499176025390625,
 0.005580902099609375,
 -0.0094146728515625,
 0.0203857421875,
 0.00911712646484375,
 0.05194091796875,
 -0.006023406982421875,
 0.00798797607421875,
 0.004215240478515625,
 -0.0090179443359375,
 -0.003814697265625,
 0.0072021484375,
 0.0221405029296875,
 0.0307769775390625,
 0.01068115234375,
 0.0277557373046875,
 -0.01462554931640625,
 -0.014862060546875,
 0.03570556640625,
 0.018829345703125,
 -0.00104522705078125,
 0.0218658447265625,
 -0.006305694580078125,
 -0.01323699951171875,
 -0.00855255126953125,
 -0.027740478515625,
 0.051361083984375,
 0.0083465576171875,
 0.005352020263671875,
 -0.042816162109375,
 0.00762176513671875,
 -0.0184783935546875,
 -4.673004150390625e-05,
 0.0085906982421875,
 -0.01488494873046875,
 -0.03912353515625,
 -0.017486572265625,
 0.007110595703125,
 0.00946807861328125,
 0.03497314453125,
 -0.006122589111328125,
 -0.050811767578125,
 0.0279693603515625,
 0.01421356201171875,
 0.029022216796875,
 0.0109405517578125,
 0.047515869140625,
 -0.007640838623046875,
 -0.00133514404296875,
 -0.00528717041015625,
 0.01177978515625,
 -0.0020389556884765625,
 -0.005069732666015625,
 -0.005603790283203125,
 0.02685546875,
 -0.01352691650390625,
 -0.0244140625,
 -0.004909515380859375,
 -0.01076507568359375,
 -0.08782958984375,
 0.0274200439453125,
 0.007495880126953125,
 -0.004180908203125,
 -0.005741119384765625,
 0.0309906005859375,
 0.0193634033203125,
 -0.030609130859375,
 -0.0263824462890625,
 -0.016693115234375,
 -0.051971435546875,
 -0.031982421875,
 0.004337310791015625,
 0.022308349609375,
 0.01332855224609375,
 -0.0171966552734375,
 -0.01258087158203125,
 0.0243377685546875,
 0.0226287841796875,
 -0.050140380859375,
 -0.00890350341796875,
 0.0256805419921875,
 0.033294677734375,
 -0.0362548828125,
 0.003383636474609375,
 -0.00591278076171875,
 -0.00286102294921875,
 0.03271484375,
 -0.0011157989501953125,
 -0.0036678314208984375,
 0.0286712646484375,
 -0.0465087890625,
 -0.018280029296875,
 0.0100555419921875,
 0.023345947265625,
 -0.04974365234375,
 0.04864501953125,
 0.01611328125,
 -0.0004639625549316406,
 -3.635883331298828e-05,
 0.03515625,
 0.01018524169921875,
 -0.0292510986328125,
 -0.00013506412506103516,
 0.0025386810302734375,
 -0.00904083251953125,
 0.0193328857421875,
 0.048248291015625,
 0.0223846435546875,
 -0.023468017578125,
 0.0247650146484375,
 0.043121337890625,
 0.0499267578125,
 -0.018035888671875,
 0.00972747802734375,
 -0.0738525390625,
 0.018798828125,
 0.0248870849609375,
 -0.00815582275390625,
 0.056488037109375,
 -0.03143310546875,
 -0.01116180419921875,
 0.005680084228515625,
 0.0205841064453125,
 -0.04473876953125,
 -0.023529052734375,
 -0.01032257080078125,
 -0.0132598876953125,
 0.00185394287109375,
 0.055877685546875,
 0.030242919921875,
 0.0338134765625,
 -0.0195465087890625,
 0.0258331298828125,
 -0.02069091796875,
 0.03564453125,
 -0.049285888671875,
 0.01837158203125,
 0.0105743408203125,
 0.0362548828125,
 0.0030574798583984375,
 0.0280609130859375,
 0.032135009765625,
 -0.044097900390625,
 0.01277923583984375,
 0.01558685302734375,
 0.010162353515625,
 -0.0266571044921875,
 0.00951385498046875,
 0.043243408203125,
 0.010498046875,
 0.0009036064147949219,
 0.039825439453125,
 -0.0277099609375,
 -0.0184326171875,
 -0.0119171142578125,
 -0.0211181640625,
 0.0011882781982421875,
 0.00655364990234375,
 0.021881103515625,
 -0.050079345703125,
 -0.0296783447265625,
 -0.0027675628662109375,
 0.0030364990234375,
 0.00739288330078125,
 -0.016387939453125,
 -0.0188140869140625,
 -0.030975341796875,
 -0.0005235671997070312,
 0.0014715194702148438,
 0.00936126708984375,
 0.00827789306640625,
 0.003314971923828125,
 -0.060150146484375,
 0.0167388916015625,
 -0.0286712646484375,
 -0.0007123947143554688,
 -0.00025582313537597656,
 -0.0178985595703125,
 -0.00429534912109375,
 -0.0013523101806640625,
 0.0225067138671875,
 0.0086212158203125,
 0.0272064208984375,
 0.037384033203125,
 0.0003037452697753906,
 -0.049652099609375,
 -0.0272979736328125,
 -0.02825927734375,
 0.00957489013671875,
 0.0055694580078125,
 -0.01544189453125,
 0.01369476318359375,
 0.0303955078125,
 -0.00969696044921875,
 -0.04425048828125,
 -0.002979278564453125,
 0.016143798828125,
 0.014862060546875,
 0.027801513671875,
 -0.001865386962890625,
 -0.01483154296875,
 -0.003643035888671875,
 0.00036907196044921875,
 0.00223541259765625,
 0.0062103271484375,
 -0.02349853515625,
 -0.01342010498046875,
 -0.0256500244140625,
 0.034942626953125,
 -0.0023479461669921875,
 -0.007137298583984375,
 0.006626129150390625,
 -0.0092315673828125,
 0.006053924560546875,
 0.044281005859375,
 0.017913818359375,
 -0.03204345703125,
 -0.0237274169921875,
 -0.01216888427734375,
 -0.008819580078125,
 0.03228759765625,
 0.01216888427734375,
 -0.00466156005859375,
 0.0069427490234375,
 -0.026824951171875,
 -0.020416259765625,
 0.029388427734375,
 -0.00827789306640625,
 -0.01090240478515625,
 0.025970458984375,
 -0.00951385498046875,
 0.0293426513671875,
 0.0005269050598144531,
 -0.0074005126953125,
 0.0003409385681152344,
 0.0176849365234375,
 0.01512908935546875,
 0.00310516357421875,
 0.028411865234375,
 -0.0205535888671875,
 -0.050201416015625,
 -0.0054779052734375,
 -0.00298309326171875,
 -0.016265869140625,
 -0.01467132568359375,
 0.006198883056640625,
 -0.045684814453125,
 -0.007289886474609375,
 0.0064697265625,
 -0.029266357421875,
 -0.002552032470703125,
 -0.01087188720703125,
 0.007053375244140625,
 0.00206756591796875,
 0.03900146484375,
 0.0043182373046875,
 -0.017181396484375,
 0.012939453125,
 0.0018396377563476562,
 -0.0184783935546875,
 0.0132293701171875,
 -0.02264404296875,
 -0.0191497802734375,
 0.01629638671875,
 0.03057861328125,
 0.0053558349609375,
 -0.01739501953125,
 0.0194549560546875,
 -0.036102294921875,
 -0.0318603515625,
 0.01229095458984375,
 0.019378662109375,
 0.00768280029296875,
 -0.0099029541015625,
 0.0010280609130859375,
 0.0216522216796875,
 -0.0110015869140625,
 -0.01580810546875,
 0.038330078125,
 0.006481170654296875,
 -0.001102447509765625,
 0.0254669189453125,
 0.01739501953125,
 0.0017423629760742188,
 0.0087738037109375,
 0.0086212158203125,
 -0.03363037109375,
 -0.0014657974243164062,
 -0.021575927734375,
 0.0126190185546875,
 -0.0142974853515625,
 -0.048675537109375,
 -0.0311431884765625,
 -0.005130767822265625,
 -0.0183258056640625,
 0.0159149169921875,

In [23]:
# api_doc_vecs = []

# for i in doc_response.data:
#     api_doc_vecs.append(i.embedding)

# 위 내용을 리스트 comprehension으로 한줄로 나타내려면

api_doc_vecs = [d.embedding for d in doc_response.data]

In [21]:
# 질문도 벡터로!

query = "우리 집 아파트는 언제 오르나요?"
api_response = client.embeddings.create(model="text-embedding-3-small", input=query)
api_response

CreateEmbeddingResponse(data=[Embedding(embedding=[-0.0177764892578125, -0.0654296875, 0.022125244140625, -0.022918701171875, -0.003833770751953125, -0.01068115234375, -0.04693603515625, -0.0345458984375, -0.00611114501953125, -0.050323486328125, -0.0230865478515625, 0.004955291748046875, 0.00421905517578125, -0.03619384765625, 0.0015506744384765625, 0.037445068359375, -0.004276275634765625, 0.0189971923828125, -0.050445556640625, -0.01812744140625, 0.0236053466796875, -0.0222625732421875, -0.04254150390625, -0.0389404296875, -0.01425933837890625, -0.0244598388671875, 0.03271484375, 0.00803375244140625, 0.0078582763671875, 0.0255889892578125, -0.041351318359375, -0.040557861328125, 0.056182861328125, 0.056884765625, -0.0070037841796875, 0.018798828125, 0.026580810546875, -0.04632568359375, -0.0255279541015625, -0.041015625, -0.004978179931640625, 0.0022430419921875, 0.0243072509765625, 0.04803466796875, -0.0159912109375, 0.076416015625, -0.0292205810546875, 0.0228271484375, 0.0122528076171875, -0.01055908203125, 0.02276611328125, 0.02191162109375, -0.0305938720703125, -0.01537322998046875, -0.0274505615234375, -0.0216217041015625, 4.601478576660156e-05, 0.03338623046875, 0.01025390625, 0.027374267578125, -0.0163421630859375, 0.03546142578125, 0.015869140625, 0.0498046875, 0.00018930435180664062, -0.0040130615234375, -0.00037479400634765625, 0.00865936279296875, 0.03253173828125, 0.05450439453125, 0.0034637451171875, 0.05145263671875, 0.04425048828125, -0.031707763671875, -0.0098419189453125, -0.019287109375, -0.0445556640625, -0.03302001953125, -0.0087432861328125, 0.047454833984375, -0.0209808349609375, 0.04937744140625, -0.0706787109375, -0.003467559814453125, 0.052825927734375, -0.0172576904296875, -0.0264739990234375, 0.0071868896484375, -0.01403045654296875, 0.06402587890625, 0.0028820037841796875, 0.053436279296875, -0.06719970703125, -0.0452880859375, 0.01297760009765625, 0.01422119140625, 0.00788116455078125, 0.0032405853271484375, 0.04058837890625, 0.0024662017822265625, 0.0138702392578125, -0.0772705078125, 0.036956787109375, -0.01470184326171875, -0.0474853515625, -0.01031494140625, -0.04315185546875, -0.018310546875, -0.0003886222839355469, -0.03778076171875, -0.059234619140625, -0.0102996826171875, -0.0526123046875, -0.0618896484375, -0.0276641845703125, 0.08282470703125, -0.01812744140625, -0.0596923828125, 0.03167724609375, -0.03631591796875, 0.0283966064453125, 0.0149993896484375, -0.041015625, 0.0180206298828125, -0.0305938720703125, 0.034912109375, -0.00592041015625, 0.0006136894226074219, -0.042144775390625, -0.0025310516357421875, -0.006687164306640625, -0.0377197265625, -0.0019054412841796875, 0.01971435546875, -0.00015974044799804688, 0.058929443359375, 0.00696563720703125, -0.0616455078125, -0.00815582275390625, 0.028656005859375, 0.04547119140625, 0.0268707275390625, 0.004016876220703125, -0.01678466796875, 0.0103759765625, 0.0174407958984375, 0.00609588623046875, -0.0305633544921875, 0.034271240234375, 0.0015821456909179688, 0.01323699951171875, -0.032379150390625, -0.01593017578125, 0.0028533935546875, 0.02581787109375, -0.00885772705078125, 0.026336669921875, 0.0255126953125, -0.0261993408203125, 0.0255889892578125, -0.0158843994140625, -0.0010690689086914062, -0.0185546875, -0.034698486328125, 0.048614501953125, 0.06854248046875, 0.0305633544921875, 0.014068603515625, -0.030029296875, 0.004180908203125, 0.037261962890625, -0.0184783935546875, -0.022918701171875, 0.058807373046875, 0.06268310546875, -0.0364990234375, 1.1563301086425781e-05, 0.007541656494140625, 0.01141357421875, 0.0242919921875, -0.0246429443359375, -0.0226593017578125, -0.0313720703125, -0.02349853515625, -0.03509521484375, -0.0017910003662109375, -0.0177764892578125, 0.08001708984375, -0.0071868896484375, 0.0292816162109375, 0.0002560615539550781, -0.0237884521484375, -0.04071044921875, 0.0002608299255371094, 0.034637451171875, -0.056549072265625, -0.0097808837890625, -0.08782958984375, 0.0266876220703125, 0.03521728515625, -0.0281524658203125, 0.017303466796875, -0.01442718505859375, -0.0162200927734375, 0.051971435546875, -0.034423828125, 0.009033203125, -0.035797119140625, 0.0435791015625, 0.00498199462890625, 0.03594970703125, -0.02093505859375, 0.0204925537109375, 0.01129913330078125, 0.0379638671875, -0.06207275390625, 0.031036376953125, 0.0294189453125, 0.01071929931640625, 0.018829345703125, -0.039825439453125, 0.00901031494140625, -0.004913330078125, 0.0230865478515625, 0.002063751220703125, 0.0229034423828125, -0.0010480880737304688, 0.02337646484375, 0.05157470703125, -0.0275421142578125, -0.0296630859375, -0.01186370849609375, -0.02362060546875, -0.019500732421875, 0.006317138671875, 0.04241943359375, -0.01404571533203125, -0.02679443359375, 0.0023174285888671875, 0.0557861328125, 0.0037784576416015625, 0.044158935546875, -0.004062652587890625, 0.063720703125, 0.004894256591796875, -0.047576904296875, 0.035369873046875, 0.0177154541015625, 0.0040130615234375, 0.03314208984375, 0.006687164306640625, 0.01479339599609375, -0.0192718505859375, -0.01122283935546875, 0.01158905029296875, 0.02435302734375, -0.0011425018310546875, -0.0151824951171875, -0.045989990234375, -0.021759033203125, 0.039215087890625, 0.00658416748046875, 0.031982421875, 0.003936767578125, -0.003810882568359375, -0.047088623046875, 0.040252685546875, 0.0227813720703125, 0.004547119140625, -0.0162200927734375, -0.040008544921875, -0.01678466796875, 0.0031452178955078125, 0.013214111328125, 0.02935791015625, -0.0023365020751953125, -0.01381683349609375, -0.0079498291015625, -0.0006279945373535156, -0.0082855224609375, -0.0023479461669921875, -0.0194244384765625, 0.0097198486328125, -0.015869140625, -0.0106964111328125, -0.0038967132568359375, -0.0299835205078125, 0.0220947265625, -0.01490020751953125, -0.00603485107421875, 0.0009732246398925781, -0.032806396484375, 0.0035114288330078125, 0.01247406005859375, 0.0099334716796875, 0.02508544921875, 0.016021728515625, -0.05877685546875, 0.0272216796875, -0.0084228515625, 0.034149169921875, 0.0010995864868164062, 0.0357666015625, 0.00821685791015625, -0.0238037109375, 0.01422882080078125, -0.0172271728515625, 0.032684326171875, 0.049530029296875, 0.040374755859375, -9.179115295410156e-05, 0.002384185791015625, 0.00728607177734375, -0.00600433349609375, -0.01267242431640625, -0.007049560546875, -0.005771636962890625, -0.0465087890625, 0.038787841796875, -0.038360595703125, -0.009124755859375, -0.0338134765625, -0.0380859375, -0.0020160675048828125, -0.0093994140625, -0.0129547119140625, 0.0012845993041992188, -0.0274810791015625, -0.0194854736328125, -0.0281219482421875, -0.0232391357421875, -0.05828857421875, 0.047332763671875, 0.0313720703125, 0.0531005859375, 0.06304931640625, 0.0028820037841796875, -0.0113983154296875, 0.03887939453125, -0.041900634765625, -0.009674072265625, -0.00261688232421875, -0.036376953125, 0.0321044921875, 0.02410888671875, -0.021514892578125, 0.0006718635559082031, -0.060089111328125, -0.0132293701171875, 0.05108642578125, 0.0125579833984375, -0.01959228515625, -0.03533935546875, 0.04388427734375, -0.0160064697265625, -0.0231475830078125, 0.041595458984375, 0.01800537109375, -0.057281494140625, 0.0396728515625, -0.053466796875, -0.02862548828125, -0.0129547119140625, -0.01374053955078125, -0.0179595947265625, 0.01488494873046875, -0.0295257568359375, 0.0377197265625, 0.0257110595703125, -0.032073974609375, -0.0643310546875, -0.0192108154296875, -0.0302734375, -0.01837158203125, -0.022064208984375, 0.10845947265625, 0.048370361328125, -0.0146026611328125, 0.046173095703125, -0.024627685546875, -0.0115509033203125, 0.01375579833984375, -0.01800537109375, -0.0265350341796875, 0.062347412109375, -0.009490966796875, -0.021942138671875, -0.003200531005859375, -0.004451751708984375, 0.0128936767578125, 0.0085601806640625, 0.002063751220703125, -0.017181396484375, 0.01593017578125, -0.0009284019470214844, -0.041473388671875, -0.0009288787841796875, -0.02435302734375, -0.0227203369140625, -0.018280029296875, 0.035369873046875, -0.033966064453125, 0.03778076171875, -0.00714874267578125, -0.050537109375, -0.0305328369140625, 0.025726318359375, -0.0246429443359375, 0.01560211181640625, 0.00830078125, -0.041778564453125, -0.05859375, 0.0272369384765625, -0.01497650146484375, 0.006397247314453125, -0.0144500732421875, 0.03802490234375, -0.01033782958984375, 0.00800323486328125, 0.021087646484375, -0.002185821533203125, 0.04083251953125, 0.006824493408203125, -0.040130615234375, -0.040618896484375, 0.00955963134765625, 0.0311126708984375, 0.0016374588012695312, -0.05609130859375, -0.00531768798828125, 0.0261993408203125, -0.06036376953125, -0.04815673828125, 0.041290283203125, -0.0236358642578125, 0.034637451171875, -0.038360595703125, 0.047698974609375, 0.0203857421875, 0.0401611328125, 0.038665771484375, -0.01418304443359375, -0.053497314453125, 0.0083465576171875, -0.0186614990234375, -0.018829345703125, 0.034393310546875, 0.006671905517578125, 0.0008535385131835938, 0.03955078125, -0.03369140625, -0.038421630859375, 0.0391845703125, -0.0136566162109375, -0.0207366943359375, -0.015869140625, -0.0223388671875, 0.01361083984375, 0.0115203857421875, -0.0080413818359375, -0.0006656646728515625, -0.0033969879150390625, -0.00954437255859375, 0.0239105224609375, 0.0413818359375, -0.018951416015625, -0.045867919921875, 0.0040130615234375, -0.0105133056640625, -0.01111602783203125, 0.0259857177734375, 0.0152740478515625, 0.025787353515625, 0.0076904296875, -0.01149749755859375, -0.017608642578125, -0.00577545166015625, 0.0374755859375, 0.0028705596923828125, -0.0174102783203125, 0.00960540771484375, 0.07720947265625, 0.008819580078125, 0.01253509521484375, -0.0273895263671875, 0.01441192626953125, -0.01806640625, -0.013580322265625, -0.043548583984375, 0.005382537841796875, 0.0027923583984375, 0.00572967529296875, 0.002567291259765625, -0.004985809326171875, -0.0035419464111328125, -0.00394439697265625, 0.03973388671875, -0.01507568359375, -0.007083892822265625, 0.0099334716796875, -0.0268707275390625, -0.0246124267578125, 0.0166778564453125, 0.01148223876953125, 0.01409912109375, -0.04827880859375, -0.0100860595703125, -0.01230621337890625, -0.0266876220703125, -0.017578125, -0.0352783203125, 0.07086181640625, -0.00982666015625, 0.001293182373046875, -0.00469970703125, 0.016387939453125, 0.00601959228515625, 0.030303955078125, -0.04205322265625, -0.002162933349609375, -0.01025390625, 0.00848388671875, -0.030670166015625, -0.009796142578125, 0.0236053466796875, 0.0281219482421875, -0.00858306884765625, -0.01763916015625, -0.0008544921875, 0.039398193359375, 0.021820068359375, -0.003978729248046875, -0.01438140869140625, 0.007030487060546875, 0.017364501953125, 0.0110015869140625, 0.040985107421875, -0.03314208984375, 0.01236724853515625, -0.037384033203125, 0.0267486572265625, -0.0240478515625, 0.03240966796875, -0.04425048828125, -0.004459381103515625, -0.0088958740234375, -0.00659942626953125, 0.01221466064453125, 0.0006122589111328125, 0.0275115966796875, 0.00577545166015625, 0.04217529296875, 0.0012655258178710938, -0.0036029815673828125, 0.019622802734375, 0.0396728515625, 0.05450439453125, 0.0094146728515625, 0.0081939697265625, -0.01233673095703125, -0.02484130859375, 0.035858154296875, -0.007354736328125, -0.006519317626953125, 0.0184478759765625, -0.0670166015625, 0.024749755859375, -0.00905609130859375, 0.0015163421630859375, -0.006877899169921875, 0.0022144317626953125, 0.03497314453125, 0.0213775634765625, 0.024993896484375, -0.0355224609375, -0.032379150390625, 0.022735595703125, 0.0018529891967773438, -3.987550735473633e-05, -0.00724029541015625, -0.006534576416015625, 0.00991058349609375, -0.01331329345703125, 0.037200927734375, 0.01007080078125, -0.01488494873046875, -0.0136566162109375, 0.024993896484375, -0.0033092498779296875, -0.0098876953125, 0.001094818115234375, -0.00469970703125, -0.01224517822265625, 5.030632019042969e-05, -0.03179931640625, -0.0198974609375, 0.008270263671875, 0.04632568359375, 0.00250244140625, 0.019683837890625, -0.009765625, -0.018707275390625, 0.033935546875, -0.008392333984375, 0.0036525726318359375, 0.00785064697265625, -0.02655029296875, -0.0034999847412109375, -0.003055572509765625, -0.0142822265625, -0.0045166015625, -0.01904296875, 0.0143280029296875, 0.035614013671875, -0.0011396408081054688, 0.0258941650390625, -0.03790283203125, 0.032623291015625, -0.03662109375, 0.005992889404296875, -0.048095703125, 0.01259613037109375, 0.01422882080078125, 0.047821044921875, 0.019989013671875, -0.03204345703125, 0.00925445556640625, -4.1484832763671875e-05, 0.0020313262939453125, -0.0234375, 0.0306854248046875, 0.01165008544921875, -0.0007295608520507812, -0.035400390625, 0.0046234130859375, 0.0298614501953125, 0.0260467529296875, 0.01050567626953125, -0.00023484230041503906, 0.047332763671875, -0.038330078125, 0.045013427734375, -0.0191192626953125, -0.0163726806640625, -0.005428314208984375, -0.0029659271240234375, 0.01271820068359375, -0.00724029541015625, -0.0306243896484375, 0.009185791015625, 0.009429931640625, -0.024383544921875, -0.0153045654296875, -0.00949859619140625, 0.00917816162109375, 0.0157928466796875, -0.0035247802734375, 0.014862060546875, -0.00908660888671875, 0.0121917724609375, -0.0162506103515625, 0.0158233642578125, -0.00022363662719726562, 0.031982421875, 0.001178741455078125, 0.0083770751953125, -0.0041961669921875, 0.0030727386474609375, 0.01116180419921875, 0.00039505958557128906, 0.03173828125, 0.0106353759765625, -0.0121917724609375, 0.0064239501953125, 0.01275634765625, 0.005390167236328125, -0.01447296142578125, -0.01375579833984375, -0.031494140625, 0.0158233642578125, -0.002033233642578125, 0.022674560546875, -0.0098724365234375, -0.0193634033203125, 0.032379150390625, 0.01617431640625, 0.018890380859375, -0.0151824951171875, 0.01117706298828125, -0.0015354156494140625, -0.02557373046875, 0.00809478759765625, 0.01364898681640625, -0.002292633056640625, 0.0452880859375, 0.007335662841796875, -0.0260162353515625, 0.0028972625732421875, 0.0004038810729980469, -0.006137847900390625, 0.01041412353515625, 0.043670654296875, 0.0092010498046875, 0.0017423629760742188, -0.008453369140625, 0.004039764404296875, 0.011260986328125, -0.0309295654296875, 0.0267181396484375, -0.0239410400390625, 0.039825439453125, -0.005947113037109375, 0.002658843994140625, -0.01385498046875, -0.0082244873046875, 0.007793426513671875, -0.01561737060546875, 0.027099609375, -0.039306640625, -0.00222015380859375, 0.006458282470703125, 0.0243682861328125, 0.03363037109375, 0.0208282470703125, 0.00399017333984375, -0.0180511474609375, -0.01605224609375, 0.03619384765625, -0.04864501953125, 0.041473388671875, 0.03289794921875, 0.0035381317138671875, 0.00835418701171875, -0.01324462890625, 0.004608154296875, -0.00475311279296875, -0.00377655029296875, 0.004673004150390625, -0.036956787109375, -0.0019397735595703125, 0.0399169921875, -0.04248046875, -0.0067596435546875, -0.0176849365234375, 0.01953125, -0.007701873779296875, -0.02203369140625, -0.04339599609375, -0.034393310546875, 0.06060791015625, -0.00992584228515625, 0.0025844573974609375, -0.0269927978515625, -0.00936126708984375, -0.0218963623046875, -0.01348114013671875, 0.041656494140625, 0.01276397705078125, 0.0070037841796875, -0.04083251953125, 0.0211334228515625, 0.0018701553344726562, 0.0008335113525390625, 0.0206146240234375, 0.0509033203125, 0.0268402099609375, -0.0728759765625, 0.040191650390625, -0.0316162109375, 0.0290069580078125, -0.01031494140625, 0.01262664794921875, 0.0189208984375, -0.01323699951171875, 0.0194854736328125, 0.0038738250732421875, -0.0293426513671875, -0.01507568359375, -0.007595062255859375, 0.00856781005859375, 0.00147247314453125, -0.032562255859375, 0.042510986328125, -0.00220489501953125, -0.0404052734375, 0.0208740234375, 0.027862548828125, -0.00826263427734375, 0.02557373046875, 0.00859832763671875, -0.00957489013671875, -0.01306915283203125, -0.00994110107421875, -0.043487548828125, 0.01422882080078125, -0.01308441162109375, -0.0021038055419921875, 0.016204833984375, -0.03485107421875, -0.041717529296875, 0.0158233642578125, -0.052093505859375, -0.00079345703125, -0.0207366943359375, -0.003429412841796875, 0.021453857421875, -0.003093719482421875, 0.042022705078125, -0.0200653076171875, -0.0234222412109375, -0.0129852294921875, 0.01488494873046875, 0.012176513671875, -0.006496429443359375, 0.038177490234375, 0.01513671875, 0.05419921875, -0.018585205078125, 0.01444244384765625, 0.0018854141235351562, 0.04736328125, -0.0269927978515625, 0.005584716796875, -0.00310516357421875, 0.0156707763671875, 0.0026035308837890625, 0.0290374755859375, -0.0289459228515625, -0.02252197265625, -0.006195068359375, -0.005771636962890625, 0.0008115768432617188, -0.0162353515625, -0.0040130615234375, -0.0035877227783203125, 0.0201568603515625, 0.01323699951171875, 0.0067291259765625, -0.03656005859375, 0.007537841796875, 0.02557373046875, 0.00997161865234375, -0.01519012451171875, -0.011260986328125, -0.0318603515625, -0.027557373046875, 0.006320953369140625, -0.0007300376892089844, -0.02655029296875, -0.0017557144165039062, 0.01812744140625, -0.00727081298828125, 0.0046234130859375, -0.004993438720703125, -0.0083160400390625, -0.060546875, -0.0038661956787109375, 0.032135009765625, 0.046234130859375, 0.01062774658203125, -0.0130462646484375, -0.009307861328125, 0.007366180419921875, -0.01190185546875, 0.000823974609375, 0.037200927734375, -0.014190673828125, 0.0136260986328125, -0.01922607421875, -0.005771636962890625, -0.032958984375, 0.00037026405334472656, -0.010650634765625, 0.002315521240234375, 0.004192352294921875, -0.005435943603515625, 0.007556915283203125, 0.052978515625, 0.018310546875, -0.018157958984375, 0.0109405517578125, 0.01043701171875, 0.01226043701171875, 0.0208740234375, -0.031005859375, -0.01552581787109375, 0.0106964111328125, 0.013397216796875, 0.00799560546875, 0.010223388671875, 0.03521728515625, 0.0265350341796875, 0.03399658203125, -0.00331878662109375, 0.0297088623046875, -0.044708251953125, -0.01419830322265625, -0.002292633056640625, -0.004306793212890625, 0.01497650146484375, 0.005207061767578125, 0.006805419921875, 0.002765655517578125, 0.0565185546875, -0.026275634765625, 0.002300262451171875, 0.00211334228515625, 0.019256591796875, 0.046051025390625, -0.0153961181640625, 0.0124664306640625, 0.0011034011840820312, 0.029083251953125, -0.03021240234375, 0.00545501708984375, 0.04302978515625, 0.0244293212890625, -0.0144805908203125, -0.01702880859375, 0.047393798828125, -0.0264739990234375, 0.0478515625, -0.00897979736328125, 0.006160736083984375, -0.01256561279296875, -0.004909515380859375, -0.04583740234375, -0.01000213623046875, -0.015960693359375, -0.0255279541015625, -0.0033359527587890625, -0.017364501953125, -0.0042572021484375, 0.0239105224609375, 0.035552978515625, 0.0003058910369873047, -0.044403076171875, -0.00933074951171875, -0.00655364990234375, 0.005542755126953125, 0.0127410888671875, -0.0210723876953125, 0.04815673828125, -0.042724609375, 0.0171966552734375, -0.06781005859375, 0.0303802490234375, -0.04119873046875, -0.01407623291015625, -0.0201873779296875, -0.0018129348754882812, 0.005908966064453125, -0.0178985595703125, -0.0172576904296875, 0.0078582763671875, 0.004253387451171875, -0.0250701904296875, 0.051055908203125, -0.0236358642578125, -0.0277099609375, -0.0267486572265625, 0.051666259765625, 0.0074615478515625, 0.0071258544921875, 0.004962921142578125, 0.04315185546875, -0.0087432861328125, -0.0165252685546875, 0.02398681640625, 0.021575927734375, -0.03369140625, -0.0221405029296875, -0.0206756591796875, -0.0159149169921875, 0.053436279296875, 0.0009250640869140625, 0.050933837890625, -0.0172271728515625, -0.021759033203125, 0.0008845329284667969, -0.01003265380859375, 0.012054443359375, 0.0113525390625, -0.0673828125, -0.0018291473388671875, 0.046234130859375, 0.056304931640625, 0.02093505859375, 0.0184478759765625, -0.00197601318359375, 0.0012140274047851562, 0.0154876708984375, 0.00974273681640625, -0.0039596557617

In [24]:
api_query_vec = [api_response.data[0].embedding] # 리스트안에 넣는 이유: 위의 api_doc_vecs와 형태 맞추려고

In [28]:
api_sim = cosine_similarity(api_query_vec, api_doc_vecs)[0]
api_sim

array([ 0.12344549,  0.07612205,  0.17595955,  0.15439471,  0.07907581,
        0.05586888,  0.30266432,  0.00196064,  0.15796446,  0.04465145,
        0.0444624 ,  0.04524953,  0.06272936,  0.0174554 ,  0.00260002,
        0.05671117,  0.11359961,  0.14136845,  0.05722282,  0.11369239,
        0.14999793,  0.09578419,  0.0868522 ,  0.17398512,  0.16228086,
       -0.01307989,  0.22468804,  0.03279508,  0.00966807,  0.19379186])

In [30]:
api_rank = api_sim.argsort(descending=True)
api_rank

array([ 6, 26, 29,  2, 23, 24,  8,  3, 20, 17,  0, 19, 16, 21, 22,  4,  1,
       12, 18, 15,  5, 11,  9, 10, 27, 13, 28, 14,  7, 25])

In [32]:
for rank, index in enumerate(api_rank):
    print(
        rank + 1,
        "문서 인덱스:", index.item(),
        "유사도:", api_sim[index].item()
    )

1 문서 인덱스: 6 유사도: 0.30266431994767495
2 문서 인덱스: 26 유사도: 0.22468804164147804
3 문서 인덱스: 29 유사도: 0.19379185991294906
4 문서 인덱스: 2 유사도: 0.17595954854677454
5 문서 인덱스: 23 유사도: 0.1739851159959176
6 문서 인덱스: 24 유사도: 0.16228086302750833
7 문서 인덱스: 8 유사도: 0.15796446412112852
8 문서 인덱스: 3 유사도: 0.15439471443374125
9 문서 인덱스: 20 유사도: 0.14999792500817793
10 문서 인덱스: 17 유사도: 0.14136845447289992
11 문서 인덱스: 0 유사도: 0.123445491971889
12 문서 인덱스: 19 유사도: 0.11369239135509021
13 문서 인덱스: 16 유사도: 0.11359961107826039
14 문서 인덱스: 21 유사도: 0.09578419296868522
15 문서 인덱스: 22 유사도: 0.08685219797241757
16 문서 인덱스: 4 유사도: 0.07907580517322318
17 문서 인덱스: 1 유사도: 0.07612205066324826
18 문서 인덱스: 12 유사도: 0.06272935662417738
19 문서 인덱스: 18 유사도: 0.057222817977024304
20 문서 인덱스: 15 유사도: 0.056711171503357694
21 문서 인덱스: 5 유사도: 0.05586888319169245
22 문서 인덱스: 11 유사도: 0.0452495345059608
23 문서 인덱스: 9 유사도: 0.044651454371606586
24 문서 인덱스: 10 유사도: 0.04446240108355923
25 문서 인덱스: 27 유사도: 0.032795082305110315
26 문서 인덱스: 13 유사도: 0.017455403129155535
27 문서 인덱스: 28 유사도: 0.009668070328103233
28 문서 인덱스: 14 유사도: 0.002600024736651437
29 문서 인덱스: 7 유사도: 0.0019606437641434497
30 문서 인덱스: 25 유사도: -0.013079885181153793

In [31]:
data['정제본문'][[6,26,29]]

6     교통 호재가 있는 곳에 아파트 분양이 이어지고 있어 주목을 받고 있습니다 주 한라가...
26    선제진입한 대우 롯데이어 시공능력 1 2위 삼성 현대 합류 현대엔지니어링 포스코건설...
29    경제와이드 모닝벨 조간 브리핑 장연재 조간브리핑입니다 발길 끊는 개미들 거래대금 2...
Name: 정제본문, dtype: str

### 실습
1. 주제를 정해서 문서 수집하기(공공데이터 포털 등등)
2. 질문을 했을 경우 유사한 문서를 가져오도록 코드 작성하기
3. 로컬 모델과 openai 임베딩 모델의 차이 비교해보고, 문서 정제 어떻게 할지 고민해보기
4. 결과 이상하면 질문 자체를 바꿔서 해보기! 예를 들어 질문이 더 디테일해야 할 필요

In [51]:
df = pd.read_csv("../data/전국도서관표준데이터.csv", encoding="cp949")
df.columns

Index(['도서관명', '시도명', '시군구명', '도서관유형', '휴관일', '평일운영시작시각', '평일운영종료시각',
       '토요일운영시작시각', '토요일운영종료시각', '공휴일운영시작시각', '공휴일운영종료시각', '열람좌석수', '자료수(도서)',
       '자료수(연속간행물)', '자료수(비도서)', '대출가능권수', '대출가능일수', '소재지도로명주소', '운영기관명',
       '도서관전화번호', '부지면적', '건물면적', '홈페이지주소', '위도', '경도', '데이터기준일자', '제공기관코드',
       '제공기관명'],
      dtype='str')

In [54]:
df.head(3)

,도서관명,시도명,시군구명,도서관유형,휴관일,평일운영시작시각,평일운영종료시각,토요일운영시작시각,토요일운영종료시각,공휴일운영시작시각,...,운영기관명,도서관전화번호,부지면적,건물면적,홈페이지주소,위도,경도,데이터기준일자,제공기관코드,제공기관명
0,전라남도교육청보성도서관,전라남도,보성군,공공도서관,월+법정공휴일+대체공휴일+특별한 사유로 관장이 지정한 날,09:00,18:00,09:00,17:00,09:00,...,전라남도교육청,061-852-3893,4876.0,2642.0,https://bslib.jne.go.kr/index.es?sid=a8,34.771148,127.084561,2026-01-13,7140000,전남광주통합특별시교육청
1,전라남도교육청구례도서관,전라남도,구례군,공공도서관,월+법정공휴일+대체공휴일+특별한 사유로 관장이 지정한 날,09:00,18:00,09:00,17:00,09:00,...,전라남도교육청,061-782-2366,2000.0,1940.0,https://grlib.jne.go.kr/index.es?sid=a7,35.205420,127.465290,2026-01-13,7140000,전남광주통합특별시교육청
2,전라남도교육청곡성교육문화회관,전라남도,곡성군,공공도서관,월+법정공휴일+대체공휴일+특별한 사유로 관장이 지정한 날,09:00,18:00,09:00,17:00,09:00,...,전라남도교육청,061-362-0671,4420.0,3803.0,https://gslib.jne.go.kr/index.es?sid=c1,35.282157,127.289701,2026-01-13,7140000,전남광주통합특별시교육청

In [55]:
columns = ['도서관명', '시도명', '시군구명']

df = df[columns]
df.head(3)

              도서관명   시도명 시군구명
0     전라남도교육청보성도서관  전라남도  보성군
1     전라남도교육청구례도서관  전라남도  구례군
2  전라남도교육청곡성교육문화회관  전라남도  곡성군

In [61]:
df['데이터'] = df.apply(
    lambda row: f"{row['도서관명']}은 {row['시도명']} {row['시군구명']}에 있는 도서관이다.",
    axis=1
)

df.head(3)

              도서관명   시도명 시군구명                                   데이터
0     전라남도교육청보성도서관  전라남도  보성군     전라남도교육청보성도서관은 전라남도 보성군에 있는 도서관이다.
1     전라남도교육청구례도서관  전라남도  구례군     전라남도교육청구례도서관은 전라남도 구례군에 있는 도서관이다.
2  전라남도교육청곡성교육문화회관  전라남도  곡성군  전라남도교육청곡성교육문화회관은 전라남도 곡성군에 있는 도서관이다.

In [62]:
from sentence_transformers import SentenceTransformer

model = SentenceTransformer(
    "dragonkue/BGE-m3-ko",
    device="cpu"
)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/391 [00:00<?, ?it/s]

In [64]:
article_vecs = model.encode(df['데이터'].tolist(), 
                             normalize_embeddings=True,
                             batch_size=4)

In [74]:
article_vecs.shape

(3601, 1024)

In [112]:
from sentence_transformers import util

def search_text(query, k=3):    # 질문과 유사한 문서 최대 k 개 가져오기
    query_vec = model.encode("query: " + query, normalize_embeddings=True)
    similarity = util.cos_sim(query_vec, article_vecs)[0]
    for i in similarity.argsort(descending=True)[:k]:   #유사도 상위 k개만 뽑음
        i = int(i)
        print(f"{similarity[i]}, 그렇다면 {df['시군구명'].iloc[i]}에 있는 {df['도서관명'].iloc[i]}으로 가세요")

In [136]:
query = "나 경남인데 작은 도서관 가고싶어"
search_text(query,5)

0.5563572645187378, 그렇다면 김해시에 있는 한국작은도서관으로 가세요
0.5508335828781128, 그렇다면 김해시에 있는 생각이크는작은도서관으로 가세요
0.5391716957092285, 그렇다면 김해시에 있는 우리작은도서관으로 가세요
0.5029788017272949, 그렇다면 김해시에 있는 소리작은도서관으로 가세요
0.5004709959030151, 그렇다면 김해시에 있는 율하e편한작은도서관으로 가세요