### 카이제곱 검정
- 두 범주가 서로 관련있는지 검정하는 방법
- 관측 빈도와 기댓값을 비교해서 특징적인 부분을 판단

- 지금까지는 숫자를 비교
- 예) 성별에 다른 연령대 구성?

#### 1. 질문에 해당하는 내용 확정, 교차표 작성
- 성별에 따른 연령대 구성이 다른가?
- 성별과 연령대의 빈도를 교차표로 작성

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px  

plt.rcParams["font.family"] = "Malgun Gothic"   # 한글 깨짐 방지(윈도우 기본 폰트)
plt.rcParams["axes.unicode_minus"] = False

df = pd.read_csv("../data/07-9_bike_ttareungi.csv")
df.head(3)

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,202606,1201,1201. 가락시장역 3번 출구,정기권,NaN,30대,123,8750.55,78.97,339960.75,2621
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173
2,202606,3928,3928.고척아이파크아파트 106동 앞,일일권,NaN,40대,7,444.12,4.00,17254.05,148

In [2]:
data = df.dropna(subset="성별")
data.head(3)

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173
3,202606,102,102. 망원역 1번출구 앞,가족권(2시간),M,~10대,1,181.72,1.64,7060.00,66
4,202606,2265,2265. 이수고가차도 남단,일일권,F,50대,6,660.63,5.96,25665.78,220

In [3]:
table = pd.crosstab(data['성별'], data['연령대코드'])
table

연령대코드  20대  30대  40대  50대  60대  70대이상  ~10대  기타
성별
F      243  281  256  218  145     48   271  44
M      262  254  252  254  186    115   316  43

In [ ]:
from scipy import stats

chi2, p, dof, expected = stats.chi2_contingency(table)
print("카이제곱 통계량", chi2)
print("p-value", p)
print("자유도", dof)

# 결과: p가 0.05보다 낮으니 성별과 연령대 관련 있다!

카이제곱 통계량 31.3133937658121
p-value 5.442025602370897e-05
자유도 7