### 효과 크기
- p값으로는 부족한 부분 있음
- 차이가 얼마나 큰지에 대해 설명 필요할 때 있다
- 사후분석

- 표본의 크기가 크면 사소한 차이도 유의하다 나올 수 있음
- 차이가 얼마나 큰지(효과크기)

In [6]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from scipy import stats

plt.rcParams["font.family"] = "Malgun Gothic"   # 한글 깨짐 방지(윈도우 기본 폰트)
plt.rcParams["axes.unicode_minus"] = False

df = pd.read_csv("../data/07-9_bike_ttareungi.csv")
df.head(3)

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
0,202606,1201,1201. 가락시장역 3번 출구,정기권,NaN,30대,123,8750.55,78.97,339960.75,2621
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173
2,202606,3928,3928.고척아이파크아파트 106동 앞,일일권,NaN,40대,7,444.12,4.00,17254.05,148

In [7]:
data = df.dropna(subset='성별')
data.head(3)

,대여일자,대여소번호,대여소명,대여구분코드,성별,연령대코드,이용건수,운동량,탄소량,이동거리(M),이용시간(분)
1,202606,5339,5339. 은빛1단지 아파트 앞,정기권,M,~10대,15,517.56,4.65,20107.79,173
3,202606,102,102. 망원역 1번출구 앞,가족권(2시간),M,~10대,1,181.72,1.64,7060.00,66
4,202606,2265,2265. 이수고가차도 남단,일일권,F,50대,6,660.63,5.96,25665.78,220

In [9]:
# 남녀 이용건수 데이터
male = data[data['성별']=='M']['이용건수']
female = data[data['성별']=='F']['이용건수']

t, p = stats.ttest_ind(male, female, equal_var=False)
print("t:", t)
print("p-value:", p)

t: 6.877884158343051
p-value: 7.402533296533952e-12

### 효과크기 - 차이가 얼마나 크냐: Cohen's d
- 평균 차이를 표준편차로 나눈 값!
- 기준: 0.2는 작음, 0.5는 중간, 0.8부터 크다

In [11]:
import numpy as np

pooled_std = np.sqrt(((len(male) - 1) * male.var() + (len(female) - 1) * female.var()) / (len(male) + len(female) - 2))

d = (male.mean() - female.mean()) / pooled_std
print("Cohen's d:", d)

Cohen's d: 0.23859778456906258

- 평균 차이가 표준편차의 1/4 수준이다 -> 차이가 작다